version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - rate-limiter-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - rate-limiter-network
    volumes:
      - redis-data:/data

networks:
  rate-limiter-network:
    driver: bridge

volumes:
  redis-data:
